const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
module.exports = async ({ mainWindow, getState, companion, getOverlay, root, report }) => {
  const evaluate = js => mainWindow.webContents.executeJavaScript(js, true);
  const range = async (id, value) => {
    await evaluate(`(()=>{const el=document.getElementById(${JSON.stringify(id)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,${JSON.stringify(String(value))});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    await delay(100);
  };
  await range('overlay-scale', 45);
  assert.equal(getState().settings.scale, .45);
  assert.ok(getOverlay().getBounds().width <= 152);
  assert.equal(await evaluate("!!document.querySelector('.hud-goal')"), false);
  assert.match(await evaluate("document.querySelector('.hud-cs-combined').textContent"), /\d\.\d\s*\/\s*8/);
  const overlay = getOverlay();
  assert.equal(await overlay.webContents.executeJavaScript("document.querySelector('.overlay-panel').getBoundingClientRect().right <= innerWidth"), true);
  await fs.writeFile(path.join(root, 'overlay-small.png'), (await overlay.webContents.capturePage()).toPNG());
  await range('overlay-scale', 100);
  await evaluate("document.querySelector('.overlay-extras-grid').scrollIntoView({block:'start'})");
  await range('health-threshold', 30); await range('mana-threshold', 15); await range('dragon-lead', 45);
  assert.equal(getState().settings.reminders.healthThreshold, 30);
  assert.equal(getState().settings.reminders.manaThreshold, 15);
  assert.equal(getState().settings.reminders.dragonLead, 45);
  await evaluate("document.querySelector('.extras-details').open=true");
  await range('reminder-x', 35); await range('reminder-y', 25); await range('reminder-duration', 2);
  await evaluate("[...document.querySelectorAll('.extras-test-buttons button')].find(x=>x.textContent==='Test health').click()");
  for (let i=0; i<50 && !companion.getWindow(); i++) await delay(100);
  const layer = companion.getWindow(); assert.ok(layer);
  for (let i=0; i<30; i++) { if (await layer.webContents.executeJavaScript("!!document.querySelector('.reminder-card')")) break; await delay(50); }
  assert.equal(layer.isAlwaysOnTop(), true); assert.equal(layer.isFocusable(), false); assert.equal(layer.isVisible(), true);
  assert.equal(await layer.webContents.executeJavaScript("document.querySelector('.reminder-card').textContent.includes('30% remaining')"), true);
  const location = await layer.webContents.executeJavaScript("(()=>{const r=document.querySelector('.reminder-card').getBoundingClientRect();return {x:(r.left+r.width/2)/innerWidth,y:r.top/innerHeight};})()");
  assert.ok(Math.abs(location.x - .35) < .02 && Math.abs(location.y - .25) < .02);
  const image = await layer.webContents.capturePage();
  assert.equal(image.toBitmap()[3], 0, 'Companion window must preserve transparent background');
  await fs.writeFile(path.join(root, 'reminder-native.png'), image.toPNG());
  await delay(2400); assert.equal(layer.isVisible(), false, 'Preview must expire and release the layer');
  await evaluate("window.rift.previewReminder('scoreboard')"); await delay(120);
  assert.equal(await layer.webContents.executeJavaScript("document.querySelectorAll('.scoreboard-row').length"), 5);
  assert.equal(await layer.webContents.executeJavaScript("document.querySelector('.scoreboard-labels').textContent.includes('Item value Δ')"), true);
  await fs.writeFile(path.join(root, 'scoreboard-native.png'), (await layer.webContents.capturePage()).toPNG());
  await delay(2200); assert.equal(layer.isVisible(), false);
  const forbidden = await layer.webContents.executeJavaScript("window.rift.previewReminder('health').then(()=>false,()=>true)");
  assert.equal(forbidden, true, 'Overlay frames cannot trigger previews');
  await evaluate("document.querySelector('.extras-details').open=false");
  await range('health-threshold', 25); await range('mana-threshold', 20); await range('dragon-lead', 30);
  await evaluate("window.rift.saveSettings({reminders:{x:50,y:40,duration:5}})");
  await delay(120);
  await fs.writeFile(path.join(root, 'overlay-extras.png'), (await mainWindow.webContents.capturePage()).toPNG());
  report.checks.push('45% native HUD, combined CS/goal, reminder thresholds, placement, expiry, preview isolation, and five-enemy item/CS comparison verified');
};
