const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const delay = ms => new Promise(resolve=>setTimeout(resolve,ms));
module.exports = async function({ app,mainWindow,getState,showOverlay,setEditing,getOverlay }) {
  const root = path.join(__dirname,'../.qa');
  const report = { passed:false, checks:[], rendererErrors:[], client:null };
  mainWindow.webContents.on('console-message',event=>{ if(event.level === 'error') report.rendererErrors.push(event.message); });
  const evaluate = js => mainWindow.webContents.executeJavaScript(js,true);
  async function until(js) { for(let i=0;i<100;i++){if(await evaluate(js))return;await delay(100);}throw new Error(`Renderer condition did not resolve: ${js}`); }
  async function snapshot(name) { await delay(400); const image=await mainWindow.webContents.capturePage(); await fs.writeFile(path.join(root,`${name}.png`),image.toPNG()); }
  async function navigate(label) { const clicked=await evaluate(`(()=>{const b=[...document.querySelectorAll('.nav-item')].find(b=>b.querySelector('span')?.textContent.trim()===${JSON.stringify(label)});if(!b)return false;b.click();return true;})()`); assert.equal(clicked,true);await delay(180); }
  try {
    await fs.mkdir(root,{recursive:true});
    mainWindow.setSize(1440,960);
    mainWindow.showInactive();
    await until(`!!document.querySelector('.sidebar')`);
    report.checks.push('Production renderer boots from local files with packaged catalog');
    await delay(2600);
    const state=getState();
    report.client={ connection:state.connection,phase:state.phase,matches:state.matches.length,live:!!state.live,hasRank:!!state.ranked };
    if(state.connection!=='offline') { assert.ok(state.summoner || state.live); report.checks.push('Actual running League client connected; account data normalized'); }
    assert.equal(await evaluate('typeof window.require'), 'undefined');
    assert.equal(await evaluate('typeof window.rift.getState'), 'function');
    report.checks.push('Renderer has isolated context and limited IPC bridge');
    await evaluate("document.querySelector('.demo-switch').click()");await delay(200);
    assert.equal(await evaluate("document.querySelector('.demo-switch').textContent.includes('on')"),true);
    assert.equal(await evaluate("document.querySelectorAll('.match-row').length"),4);
    await snapshot('overview');
    await evaluate("document.querySelector('.match-row').click()");await until("!!document.querySelector('[role=dialog]')");
    assert.equal(await evaluate("document.querySelector('.match-details').textContent.includes('Champion damage')"),true);
    await evaluate("document.querySelector('[aria-label=\"Close dialog\"]').click()");
    report.checks.push('Demo dashboard and match detail dialog function');
    await navigate('Champions');
    assert.equal(await evaluate("document.querySelectorAll('.champion-card').length"),173);
    await evaluate("(()=>{const i=document.querySelector('[aria-label=\"Filter champion library\"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(i,'Jinx');i.dispatchEvent(new Event('input',{bubbles:true}));})()");
    await until("document.querySelectorAll('.champion-card').length===1");
    assert.equal(await evaluate("document.querySelector('.champion-name').textContent"),'Jinx');
    report.checks.push('Champion library filtering works across the bundled roster');
    await evaluate("document.querySelector('.champion-card-body').click()");await until("!!document.querySelector('.build-source-bar')");
    await until("!!document.querySelector('.build-main') || !!document.querySelector('.source-error')");
    assert.equal(await evaluate("!!document.querySelector('.build-main')"),true,'Live OP.GG build must load');
    report.checks.push('Live OP.GG build and rune preset load successfully');
    await snapshot('builds');
    assert.equal(await evaluate("!!document.querySelector('.build-item .text-button')"), false);
    await evaluate("[...document.querySelectorAll('[role=tab]')].find(b=>b.textContent.includes('Rune editor')).click()");await delay(150);
    assert.equal(await evaluate("document.querySelectorAll('.rune-path-panel').length"),2);
    await evaluate("document.querySelectorAll('.rune-path-panel')[0].querySelectorAll('.rune-option')[1].click()");
    await evaluate("[...document.querySelectorAll('.rune-actions button')].find(b=>b.textContent.includes('Save locally')).click()");
    const page=await evaluate("JSON.parse(localStorage.getItem('rift.runes.Jinx'))");assert.equal(page.selectedPerkIds.length,9);
    await snapshot('runes');
    report.checks.push('Rune editor changes selections and saves locally without modifying League');
    await navigate('Match history');assert.equal(await evaluate("document.querySelectorAll('.match-row').length"),10);
    await evaluate("[...document.querySelectorAll('.segmented-control button')].find(b=>b.textContent==='Defeats').click()");await delay(100);
    assert.equal(await evaluate("document.querySelectorAll('.match-row').length"),3);
    await snapshot('history');report.checks.push('Match result filtering works');
    await navigate('Live game');assert.equal(await evaluate("!!document.querySelector('.live-player-heading')"),true);await snapshot('live');
    await evaluate("[...document.querySelectorAll('.tabs button')].find(b=>b.textContent.includes('Champion select')).click()");await delay(100);
    assert.equal(await evaluate("document.querySelectorAll('.draft-slot').length"),5);
    report.checks.push('Live stats and visible champion-select picks render correctly');
    await navigate('Overlay');
    assert.equal(await evaluate("!!document.querySelector('#target-item')"), false);
    await until("!!document.querySelector('.hud-waves img')");
    assert.match(await evaluate("document.querySelector('.hud-waves strong').textContent"), /^(~\d+|0|✓)$/);
    assert.equal(await evaluate("document.querySelector('.hud-waves .hud-label').textContent"), 'Waves to item');
    await evaluate("document.querySelector('[aria-label=\"Show Waves to item\"]').click()");await delay(180);
    assert.equal(getState().settings.widgets.waves, false);
    assert.equal(await evaluate("!!document.querySelector('.hud-waves')"), false);
    await evaluate("document.querySelector('[aria-label=\"Show Waves to item\"]').click()");await delay(180);
    assert.equal(getState().settings.widgets.waves, true);
    await until("!!document.querySelector('.hud-waves img')");
    report.checks.push('Next item loads automatically; no manual picker or build tracking buttons remain');
    await evaluate("document.querySelector('[aria-label=\"Show CS per minute\"]').click()");await delay(180);
    assert.equal(getState().settings.widgets.cs,false);
    await evaluate("document.querySelector('[aria-label=\"Show CS per minute\"]').click()");await delay(180);
    assert.equal(getState().settings.widgets.cs,true);
    await evaluate("[...document.querySelectorAll('.widget-setting button')].find(b=>b.textContent==='Number').click()");await delay(100);
    assert.equal(getState().settings.csDisplay,'number');
    assert.equal(await evaluate("!!document.querySelector('.hud-chart')"),false);
    await snapshot('overlay-number');
    await evaluate("[...document.querySelectorAll('.widget-setting button')].find(b=>b.textContent==='Graph + number').click()");await delay(100);
    assert.equal(getState().settings.csDisplay,'graph');
    assert.equal(await evaluate("!!document.querySelector('.hud-chart svg')"),true);
    await evaluate("document.querySelector('[aria-label=\"Increase CS goal\"]').click()");await delay(100);
    assert.equal(getState().settings.csTarget,8.5);
    await evaluate("document.querySelector('[aria-label=\"Decrease CS goal\"]').click()");await delay(100);
    assert.equal(getState().settings.csTarget,8);
    report.checks.push('Number/graph mode and CS goal update the preview and persist');
    await snapshot('overlay-studio');report.checks.push('Overlay widget preferences persist through IPC');
    await showOverlay(true);const overlay=getOverlay();
    for(let i=0;i<70;i++){if(await overlay.webContents.executeJavaScript("!!document.querySelector('.overlay-panel')"))break;await delay(100);}
    assert.equal(overlay.isAlwaysOnTop(),true);assert.equal(overlay.isVisible(),true);assert.equal(overlay.isFocusable(),false);
    setEditing(true);assert.equal(overlay.isFocusable(),true);await delay(100);
    assert.equal(await overlay.webContents.executeJavaScript("document.querySelector('.overlay-panel').classList.contains('editing')"),true);
    setEditing(false);assert.equal(overlay.isFocusable(),false);await delay(200);
    assert.equal(await overlay.webContents.executeJavaScript("document.querySelector('.overlay-panel').getBoundingClientRect().bottom <= innerHeight"),true);
    assert.equal(await overlay.webContents.executeJavaScript("!!document.querySelector('.overlay-panel .brand')"),false);
    const overlayCapture = await overlay.webContents.capturePage();
    await fs.writeFile(path.join(root,'native-overlay.png'),overlayCapture.toPNG());
    const captureSize = overlayCapture.getSize();
    assert.equal(overlayCapture.toBitmap()[((captureSize.height - 2) * captureSize.width + 2) * 4 + 3], 0, 'Outside the overlay panel must be fully transparent');
    report.checks.push('Native overlay preserves real pixel transparency outside the HUD');
    const testSnapshot = { ...getState(), settings: { ...getState().settings }, live: { ...getState().live, championId: 'Ahri', role: 'auto', time: 900, gameMode: 'CLASSIC', mapNumber: 11, gold: 0, cs: 100, csPerMin: 6.67, vision: 12, items: [], csHistory: [] } };
    overlay.webContents.send('rift:state', testSnapshot);await delay(200);
    const waveText = () => overlay.webContents.executeJavaScript("Number(document.querySelector('.hud-waves strong').textContent.replace('~',''))");
    const firstItem = await overlay.webContents.executeJavaScript("Number(document.querySelector('.hud-waves').dataset.nextItem)");
    assert.ok(firstItem > 0);
    const beforeReward = await waveText();
    overlay.webContents.send('rift:state', { ...testSnapshot, live: { ...testSnapshot.live, gold: 450 } });await delay(100);
    assert.ok(await waveText() < beforeReward, 'Fresh kill/assist gold must reduce the visible wave estimate');
    overlay.webContents.send('rift:state', { ...testSnapshot, live: { ...testSnapshot.live, items: [{ id: firstItem, count: 1 }] } });await delay(100);
    const nextItem = await overlay.webContents.executeJavaScript("Number(document.querySelector('.hud-waves').dataset.nextItem)");
    assert.ok(nextItem > 0 && nextItem !== firstItem, 'Completing an item must automatically advance the target');
    report.checks.push('Buying the next item automatically advances the native tracker');
    overlay.webContents.send('rift:state', getState());await delay(100);
    const lastPoll = getState().lastUpdated;
    for (let i=0;i<90 && getState().lastUpdated===lastPoll;i++) await delay(100);
    assert.notEqual(getState().lastUpdated, lastPoll, 'Live state must refresh within ten seconds');
    report.checks.push('New reward gold recalculates the native HUD; automatic live polling stays below ten seconds');
    await showOverlay(false);assert.equal(overlay.isVisible(),false);
    report.checks.push('Native overlay is always on top, unlocks for dragging, relocks without focus, and hides');
    await navigate('Settings');await snapshot('settings');
    assert.equal(await evaluate("document.querySelector('.about-info').textContent.includes('Riot Data Dragon')"),true);
    assert.equal(await evaluate("document.querySelector('[aria-label=\"Automatically download app updates\"]').getAttribute('aria-checked')"),'true');
    assert.equal(getState().updates.status,'unsupported');
    assert.equal(getState().settings.updateUrl,require('../electron/update-config.json').url);
    const rejected=await evaluate("window.rift.updates('configure','http://example.com/unsafe')");assert.equal(rejected.ok,false);assert.equal(getState().settings.updateUrl,require('../electron/update-config.json').url);
    await evaluate("document.querySelector('.update-settings').scrollIntoView({block:'center'})");await snapshot('updates');
    report.checks.push('Automatic downloads default on, GitHub release server is preconfigured, and unsafe URLs are rejected');
    const preferences=await fs.readFile(path.join(app.getPath('userData'),'preferences.json'),'utf8');
    assert.equal(preferences.includes('password'),false);assert.equal(preferences.includes('Authorization'),false);
    report.checks.push('Preferences contain no League authentication token');
    await navigate('Your stats');
    mainWindow.setMinimumSize(300,300);
    for (const [width,height] of [[1024,768],[768,1024],[375,812],[812,375]]) {
      mainWindow.setSize(width,height);await delay(150);
      assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth"),true,`No page overflow at ${width}`);
      assert.equal(await evaluate("document.querySelector('.workspace').scrollWidth <= document.querySelector('.workspace').clientWidth + 1"),true,`No content overflow at ${width}`);
      await snapshot(`responsive-${width}`);
    }
    mainWindow.setSize(375,812);
    await navigate('Overlay');await snapshot('overlay-mobile');
    assert.equal(await evaluate("document.querySelector('.workspace').scrollWidth <= document.querySelector('.workspace').clientWidth + 1"),true);
    mainWindow.setSize(1440,960);
    report.checks.push('Layout fits 375, 768, 1024, and 1440 pixels, including landscape and overlay settings');
    assert.equal(report.rendererErrors.length,0,report.rendererErrors.join('\n'));
    report.passed=true;
  } catch(error) { report.error=error.stack;console.error(error.stack); }
  await fs.writeFile(path.join(root,'desktop-report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
  app.exit(report.passed?0:1);
};
