import { useEffect, useRef } from 'react';
import { ArrowUpRight, Check, ChevronRight, Crosshair, Flame, Layers, Shield, Sparkles, Star, Swords, X } from 'lucide-react';
import type { ReactNode } from 'react';
import type { Catalog, Champion, Match, Live, Settings } from './types';
import { duration, guideFor, itemImage, portrait, queueName, resource, strip, timeAgo } from './data';
export function Logo({ small=false }: { small?:boolean }) { return <div className={`brand ${small?'brand-small':''}`}><span>DPM<span className="brand-dot">.lol</span></span></div>; }
export function Badge({ children, color='' }: { children: ReactNode; color?:string }) { return <span className={`badge ${color}`}>{children}</span>; }
export function RoleIcon({ role, size=18 }: { role:string; size?:number }) { const Icon = role === 'Marksman' || role === 'Bottom' ? Crosshair : role === 'Tank' || role === 'Support' ? Shield : role === 'Assassin' || role === 'Jungle' ? Swords : role === 'Mage' || role === 'Mid' ? Sparkles : Flame; return <Icon size={size}/>; }
export function ChampionImage({ champion, catalog, className='' }: { champion:Champion | undefined; catalog:Catalog; className?:string }) { return champion ? <img className={`champion-image ${className}`} src={portrait(champion.id,catalog.version)} alt={champion.name} loading="lazy" onError={event=>{event.currentTarget.style.opacity='0.2';}}/> : <div className={`champion-placeholder ${className}`}><Swords size={20}/></div>; }
export function ItemIcon({ id, catalog, large=false }: { id:number; catalog:Catalog; large?:boolean }) {
  const item = catalog.items[String(id)];
  return <span className={`item-icon ${large?'large':''}`} tabIndex={0}><img src={itemImage(id,catalog.version)} alt={item?.name || `Item ${id}`} loading="lazy"/><span className="item-tooltip"><strong>{item?.name || `Item ${id}`}</strong><span>{item?.gold?.total?.toLocaleString()} gold</span><small>{strip(item?.description || '')}</small></span></span>;
}
export function ChampionCard({ champion,catalog,favorite,onFavorite,onSelect }: { champion:Champion; catalog:Catalog; favorite:boolean; onFavorite():void; onSelect():void }) {
  const guide=guideFor(champion);
  return <article className="champion-card"><button className="card-favorite icon-button" aria-label={`${favorite?'Unfavorite':'Favorite'} ${champion.name}`} aria-pressed={favorite} onClick={onFavorite}><Star size={15} fill={favorite?'currentColor':'none'}/></button><button className="champion-card-body" onClick={onSelect}><ChampionImage champion={champion} catalog={catalog}/><div className="champion-name">{champion.name}</div><div className="champion-title">{champion.title}</div><div className="champion-card-bottom"><span><RoleIcon role={guide.role} size={13}/>{guide.role}</span><ChevronRight size={15}/></div></button></article>;
}
export function MatchRow({ match,catalog,onClick }: { match:Match; catalog:Catalog; onClick():void }) {
  const champion = catalog.champions.find(c=>c.key===match.championKey);
  return <button className={`match-row ${match.win?'win':'loss'}`} onClick={onClick}><span className="match-outcome">{match.win?'VICTORY':'DEFEAT'}<small>{queueName(match.queueId)}</small></span><ChampionImage champion={champion} catalog={catalog}/><span className="match-champion"><strong>{champion?.name || 'Champion'}</strong><small>{timeAgo(match.timestamp)}</small></span><span className="match-kda"><strong>{match.kills} <span>/ {match.deaths} /</span> {match.assists}</strong><small>{((match.kills+match.assists)/Math.max(match.deaths,1)).toFixed(2)} KDA</small></span><span className="match-cs"><strong>{match.cs} CS</strong><small>{(match.cs/(match.duration/60||1)).toFixed(1)} / min</small></span><span className="match-items">{match.items.slice(0,6).map((id,i)=><img key={`${id}-${i}`} src={itemImage(id,catalog.version)} alt={catalog.items[String(id)]?.name || 'Item'} loading="lazy"/>)}</span><span className="match-duration">{duration(match.duration)}</span><ChevronRight size={16}/></button>;
}
export function EmptyState({ icon, title, body, action }: { icon:ReactNode; title:string; body:string; action?:ReactNode }) { return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{body}</p>{action}</div>; }
export function Toggle({ checked,onChange,label }: { checked:boolean; onChange(value:boolean):void; label:string }) { return <button className={`toggle ${checked?'on':''}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>; }
export function Modal({ children,title,onClose }: { children:ReactNode; title:string; onClose():void }) {
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=> { const original=document.activeElement as HTMLElement | null; ref.current?.querySelector<HTMLButtonElement>('button')?.focus(); const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape') onClose(); if(e.key==='Tab') { const nodes=ref.current?.querySelectorAll<HTMLElement>('button,input,select,[tabindex="0"],a[href]'); if(!nodes?.length) return; const first=nodes[0], last=nodes[nodes.length-1]; if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();} }}; document.addEventListener('keydown',onKey); return ()=> { document.removeEventListener('keydown',onKey); original?.focus(); }; },[onClose]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</div></div>;
}
export function MatchDetails({ match,catalog }: { match:Match; catalog:Catalog }) { const champion=catalog.champions.find(c=>c.key===match.championKey); return <div className="match-details"><div className="match-detail-heading"><ChampionImage champion={champion} catalog={catalog}/><div><Badge color={match.win?'green':'red'}>{match.win?'Victory':'Defeat'}</Badge><h2>{champion?.name}</h2><p>{queueName(match.queueId)} · {duration(match.duration)} · {new Date(match.timestamp).toLocaleString()}</p></div></div><div className="detail-stats">{[['K / D / A',`${match.kills} / ${match.deaths} / ${match.assists}`],['Creep score',`${match.cs} · ${(match.cs/(match.duration/60||1)).toFixed(1)}/min`],['Champion damage',match.damage.toLocaleString()],['Gold earned',match.gold.toLocaleString()]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="section-label">FINAL BUILD</div><div className="item-line">{match.items.map((id,i)=><ItemIcon key={`${id}-${i}`} id={id} catalog={catalog} large/>)}</div></div>; }
export { default as OverlayPanel } from './Overlay';
export function SectionHeading({ title,detail,action }: { title:string; detail?:string; action?:ReactNode }) { return <div className="section-heading"><div><h2>{title}</h2>{detail&&<p>{detail}</p>}</div>{action}</div>; }
export function GuideLink({ onClick }: { onClick():void }) { return <button className="text-button" onClick={onClick}>View guide <ArrowUpRight size={15}/></button>; }
export { Layers };
