import { useEffect, useState } from 'react';
import { ArrowDownToLine, Check, CloudDownload, Download, ExternalLink, Info, LoaderCircle, RefreshCw, RotateCw } from 'lucide-react';
import type { AppState, Settings } from './types';
import { Badge, SectionHeading, Toggle } from './components';
async function action(type:'configure'|'check'|'install', onToast:(message:string)=>void,url?:string) {
  if(!window.rift){onToast('App updates are available in the installed Windows launcher.');return;}
  try { const result=await window.rift.updates(type,url);onToast(result.message); } catch {onToast('The update action could not finish. Please try again.');}
}
export function UpdatePreferences({state,saveSettings,onToast}:{state:AppState;saveSettings(input:Partial<Settings>):Promise<void>;onToast(message:string):void}) {
  const [url,setUrl]=useState(state.settings.updateUrl);
  const [saving,setSaving]=useState(false);
  useEffect(()=>setUrl(state.settings.updateUrl),[state.settings.updateUrl]);
  const status=state.updates;
  const save=async()=>{setSaving(true);await action('configure',onToast,url);setSaving(false);};
  return <section className="panel update-settings"><SectionHeading title="Launcher updates" action={<Badge color={status.status==='ready'?'green':status.status==='unconfigured'?'':'purple'}>{status.status==='unconfigured'?'SERVER NOT SET':status.status.toUpperCase()}</Badge>}/><div className="update-settings-grid"><div><div className="setting-row update-toggle"><div><strong>Automatically download new versions</strong><small>Check on launch and every four hours. New releases download in the background.</small></div><Toggle label="Automatically download app updates" checked={state.settings.autoDownloadUpdates} onChange={value=>saveSettings({autoDownloadUpdates:value})}/></div><label className="update-url-label" htmlFor="release-url">Release server URL</label><div className="update-url-field"><input id="release-url" type="url" aria-label="Update release server URL" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://your-server.com/updates/"/><button className="secondary-button" onClick={save} disabled={saving}>{saving?<LoaderCircle className="spin" size={14}/>:<Check size={14}/>}Save</button></div><p className="update-server-hint">Use a public GitHub repository or HTTPS release folder.</p></div><div className="update-status-card"><div className="update-status-icon">{status.status==='ready'?<Check size={25}/>:status.status==='downloading'?<CloudDownload size={25}/>:<RefreshCw size={25}/>}</div><div><strong>{status.status==='ready'?`Version ${status.availableVersion} is ready`:status.status==='downloading'?`Downloading ${status.availableVersion}`:status.status==='current'?'You’re up to date':status.status==='unconfigured'?'Update server not configured':'Update status'}</strong><p>{status.message}</p><small>Installed version: {status.version}{status.lastCheck?` · Checked ${new Date(status.lastCheck).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:''}</small></div>{status.status==='downloading'&&<div className="update-download-progress"><i style={{width:`${status.progress}%`}}/><span>{status.progress}%</span></div>}<div className="update-status-actions"><button className="secondary-button" onClick={()=>action('check',onToast)} disabled={!state.settings.updateUrl||['checking','downloading'].includes(status.status)}><RefreshCw size={13} className={status.status==='checking'?'spin':''}/>Check now</button>{status.status==='ready'&&<button className="primary-button" onClick={()=>action('install',onToast)}><RotateCw size={13}/>Restart & install</button>}</div></div></div><div className="guide-note"><Info size={15}/><span>Automatic updates use the installed launcher. New versions are verified before installation. Restarting for an update is blocked while a League game is active.</span></div></section>;
}
export function UpdateBanner({state,onToast}:{state:AppState;onToast(message:string):void}) {if(state.updates.status!=='ready')return null;return <div className="update-ready-banner" role="status"><CloudDownload size={18}/><span><strong>Version {state.updates.availableVersion} is ready.</strong><small>Your update downloaded in the background.</small></span><button className="primary-button" onClick={()=>action('install',onToast)}><RotateCw size={13}/>Restart & install</button></div>;}
